"""peer_limits

Revision ID: 04eb2d68aa9f
Revises: 8228c0622b52
Create Date: 2023-01-04 09:59:14.233161

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "04eb2d68aa9f"
down_revision = "8228c0622b52"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("instances", sa.Column("last_ingest_peers", sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instances", "last_ingest_peers")
    # ### end Alembic commands ###
