"""ban_keyword_list

Revision ID: 08e94aac57b6
Revises: e79ec4de795d
Create Date: 2022-12-26 21:21:41.929956

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "08e94aac57b6"
down_revision = "e79ec4de795d"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bans", sa.Column("keywords", sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("bans", "keywords")
    # ### end Alembic commands ###
