"""initial database

Revision ID: 235eb2654dd6
Revises: 
Create Date: 2022-12-11 16:12:41.301092

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "235eb2654dd6"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "instances",
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("last_ingest", sa.DateTime(), nullable=True),
        sa.Column("last_ingest_status", sa.String(), nullable=True),
        sa.Column("title", sa.String(), nullable=True),
        sa.Column("short_description", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("version", sa.String(), nullable=True),
        sa.Column("user_count", sa.Integer(), nullable=True),
        sa.Column("status_count", sa.Integer(), nullable=True),
        sa.Column("domain_count", sa.Integer(), nullable=True),
        sa.Column("thumbnail", sa.String(), nullable=True),
        sa.Column("registration_open", sa.Boolean(), nullable=True),
        sa.Column("approval_required", sa.Boolean(), nullable=True),
        sa.PrimaryKeyConstraint("host"),
    )
    op.create_table(
        "bans",
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("ingest_id", sa.String(), nullable=False),
        sa.Column("banned_host", sa.String(), nullable=False),
        sa.Column("severity", sa.String(), nullable=False),
        sa.Column("comment", sa.String(), nullable=True),
        sa.ForeignKeyConstraint(
            ["banned_host"],
            ["instances.host"],
        ),
        sa.ForeignKeyConstraint(
            ["host"],
            ["instances.host"],
        ),
        sa.PrimaryKeyConstraint("host", "banned_host"),
    )
    op.create_table(
        "peers",
        sa.Column("host", sa.String(), nullable=False),
        sa.Column("peer_host", sa.String(), nullable=False),
        sa.Column("ingest_id", sa.String(), nullable=False),
        sa.ForeignKeyConstraint(
            ["host"],
            ["instances.host"],
        ),
        sa.ForeignKeyConstraint(
            ["peer_host"],
            ["instances.host"],
        ),
        sa.PrimaryKeyConstraint("host", "peer_host"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("peers")
    op.drop_table("bans")
    op.drop_table("instances")
    # ### end Alembic commands ###
