"""ban_host_digest

Revision ID: 3c5b523b871c
Revises: d89c2d5ff8be
Create Date: 2022-12-30 22:22:42.558023

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "3c5b523b871c"
down_revision = "d89c2d5ff8be"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("bans", sa.Column("digest", sa.String(), nullable=True))
    op.create_index(op.f("ix_bans_digest"), "bans", ["digest"], unique=False)
    op.add_column("instances", sa.Column("digest", sa.String(), nullable=True))
    op.create_index(op.f("ix_instances_digest"), "instances", ["digest"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_instances_digest"), table_name="instances")
    op.drop_column("instances", "digest")
    op.drop_index(op.f("ix_bans_digest"), table_name="bans")
    op.drop_column("bans", "digest")
    # ### end Alembic commands ###
