"""save_web_host

Revision ID: 4cecd778ad0b
Revises: 04eb2d68aa9f
Create Date: 2023-01-06 16:32:57.048187

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4cecd778ad0b"
down_revision = "04eb2d68aa9f"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("instances", sa.Column("www_host", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instances", "www_host")
    # ### end Alembic commands ###
