"""asn

Revision ID: a2631f842ebb
Revises: b69dbaa8f2d8
Create Date: 2022-12-13 17:08:02.339339

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "a2631f842ebb"
down_revision = "b69dbaa8f2d8"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "asn",
        sa.Column("asn", sa.String(), nullable=False),
        sa.Column("cc", sa.String(), nullable=True),
        sa.Column("owner", sa.String(), nullable=True),
        sa.Column("prefix", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("asn"),
    )
    op.add_column("instances", sa.Column("ip_address", sa.String(), nullable=True))
    op.add_column("instances", sa.Column("asn", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instances", "asn")
    op.drop_column("instances", "ip_address")
    op.drop_table("asn")
    # ### end Alembic commands ###
