"""record blocked api calls

Revision ID: c5c6d2b05721
Revises: 235eb2654dd6
Create Date: 2022-12-12 19:22:06.897307

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5c6d2b05721'
down_revision = '235eb2654dd6'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('instances', sa.Column('has_public_bans', sa.Boolean(), nullable=True))
    op.add_column('instances', sa.Column('has_public_peers', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('instances', 'has_public_peers')
    op.drop_column('instances', 'has_public_bans')
    # ### end Alembic commands ###
