"""active_monthly_users

Revision ID: d2f8f060e54e
Revises: 3c5b523b871c
Create Date: 2023-01-01 21:17:42.767873

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "d2f8f060e54e"
down_revision = "3c5b523b871c"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("instance_stats", sa.Column("active_monthly_users", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instance_stats", "active_monthly_users")
    # ### end Alembic commands ###
