"""status_ingest_index

Revision ID: e79ec4de795d
Revises: 04c441968ceb
Create Date: 2022-12-17 22:36:59.230318

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "e79ec4de795d"
down_revision = "04c441968ceb"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index("idx_instance_status_time", "instances", ["last_ingest_status", "last_ingest"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("idx_instance_status_time", table_name="instances")
    # ### end Alembic commands ###
