"""instance_nodeinfo_version

Revision ID: f11ddc61016b
Revises: d2f8f060e54e
Create Date: 2023-01-01 21:33:52.112106

"""
import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f11ddc61016b"
down_revision = "d2f8f060e54e"
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("instances", sa.Column("nodeinfo_version", sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("instances", "nodeinfo_version")
    # ### end Alembic commands ###
