"""add evils

Revision ID: f4f9ee0f606b
Revises: c5c6d2b05721
Create Date: 2022-12-12 19:56:43.180939

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4f9ee0f606b'
down_revision = 'c5c6d2b05721'
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('evil',
    sa.Column('domain', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('domain')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('evil')
    # ### end Alembic commands ###
